<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

<title>1. Overview</title>

<script type="text/javascript">
window.onload = function() {
  var imgs = document.getElementsByTagName('img'), i, img;
  for (i = 0; i < imgs.length; i++) {
    img = imgs[i];
    // center an image if it is the only element of its parent
    if (img.parentElement.childElementCount === 1)
      img.parentElement.style.textAlign = 'center';
  }
};
</script>





<style type="text/css">
body, td {
   font-family: sans-serif;
   background-color: white;
   font-size: 13px;
}

body {
  max-width: 800px;
  margin: auto;
  padding: 1em;
  line-height: 20px;
}

tt, code, pre {
   font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace;
}

h1 {
   font-size:2.2em;
}

h2 {
   font-size:1.8em;
}

h3 {
   font-size:1.4em;
}

h4 {
   font-size:1.0em;
}

h5 {
   font-size:0.9em;
}

h6 {
   font-size:0.8em;
}

a:visited {
   color: rgb(50%, 0%, 50%);
}

pre, img {
  max-width: 100%;
}
pre {
  overflow-x: auto;
}
pre code {
   display: block; padding: 0.5em;
}

code {
  font-size: 92%;
  border: 1px solid #ccc;
}

code[class] {
  background-color: #F8F8F8;
}

table, td, th {
  border: none;
}

blockquote {
   color:#666666;
   margin:0;
   padding-left: 1em;
   border-left: 0.5em #EEE solid;
}

hr {
   height: 0px;
   border-bottom: none;
   border-top-width: thin;
   border-top-style: dotted;
   border-top-color: #999999;
}

@media print {
   * {
      background: transparent !important;
      color: black !important;
      filter:none !important;
      -ms-filter: none !important;
   }

   body {
      font-size:12pt;
      max-width:100%;
   }

   a, a:visited {
      text-decoration: underline;
   }

   hr {
      visibility: hidden;
      page-break-before: always;
   }

   pre, blockquote {
      padding-right: 1em;
      page-break-inside: avoid;
   }

   tr, img {
      page-break-inside: avoid;
   }

   img {
      max-width: 100% !important;
   }

   @page :left {
      margin: 15mm 20mm 15mm 10mm;
   }

   @page :right {
      margin: 15mm 10mm 15mm 20mm;
   }

   p, h2, h3 {
      orphans: 3; widows: 3;
   }

   h2, h3 {
      page-break-after: avoid;
   }
}
</style>



</head>

<body>
<h1>1. Overview</h1>

<p>This report is the second part of the Statistical Inference course project. In this report, the ToothGrowth data in the R datasets will be analyzed using some basic inferential statistics. Exploratory data analyses and summary of the data are first given. After that, comparisons of tooth growth by supp and dose are performed respectively, in which different assumptions, null hypotheses (\(H_0\)), and alternative hypotheses (\(H_a\)) are set up and tested using T test. Finally, conclusions are made based on the T statistics.</p>

<h1>2. Exploratory Analyses on ToothGrowth Data</h1>

<p>For exploratory plots, see Appendix for reference. Based on the plots, in terms of different supp (Figure 1), VC and OJ seem to have different effects on the length of tooth growth, though it is not very easy to distinguish; in terms of dose (Figure 2), a higher dose seems to increase the length of tooth growth. Both observations require two-sided hypothesis testing, which will be explained in details later.</p>

<h1>3. Basic Summary of the Data</h1>

<h2>3.1 General information:</h2>

<pre><code>##       len        supp         dose      
##  Min.   : 4.20   OJ:30   Min.   :0.500  
##  1st Qu.:13.07   VC:30   1st Qu.:0.500  
##  Median :19.25           Median :1.000  
##  Mean   :18.81           Mean   :1.167  
##  3rd Qu.:25.27           3rd Qu.:2.000  
##  Max.   :33.90           Max.   :2.000
</code></pre>

<h2>3.2 Basic summary of tooth growth by supp:</h2>

<pre><code>## $OJ
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    8.20   15.52   22.70   20.66   25.72   30.90 
## 
## $VC
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    4.20   11.20   16.50   16.96   23.10   33.90
</code></pre>

<h2>3.3 Basic summary of tooth growth by dose:</h2>

<pre><code>## $`0.5`
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   4.200   7.225   9.850  10.600  12.250  21.500 
## 
## $`1`
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   13.60   16.25   19.25   19.74   23.38   27.30 
## 
## $`2`
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   18.50   23.52   25.95   26.10   27.83   33.90
</code></pre>

<h1>4. Comparisons of Tooth Growth by Supp</h1>

<p>Assuming that &quot;len&quot; is an iid variable, the data of tooth growth by VC and OJ are both normally distributed, and the population variances are unequal.</p>

<p>\(H_0\): The length of tooth growth by VC is equivalent to the length of tooth growth by OJ (\(VC = OJ\)).</p>

<p>\(H_a\): The length of tooth growth by VC is not equivalent to the length of tooth growth by OJ (\(VC \neq  OJ\)).</p>

<p><strong>Hypothesis testing</strong>:</p>

<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  OJ and VC
## t = 1.9153, df = 55.309, p-value = 0.06063
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -0.1710156  7.5710156
## sample estimates:
## mean of x mean of y 
##  20.66333  16.96333
</code></pre>

<p>According to the statistical test, the confidence interval did not exclude zero, the absolute value of the test statistic is not greater than <code>qt(.975, 55.309)</code> = 2.0038, and the p-value is not less than the 0.05 threshold.</p>

<p><strong>Conclusion</strong>: The null hypothesis is not rejected. The length of tooth growth by VC is equivalent to the length of tooth growth by OJ (\(VC = OJ\)).</p>

<h1>5. Comparisons of Tooth Growth by Dose (Need replacement for one-sided test)</h1>

<h2>5.1 \(Dose_{0.5}\) v.s. \(Dose_{1.0}\)</h2>

<p>Assuming that &quot;len&quot; is an iid variable, the data of tooth growth by dose 0.5 and dose 1.0 are normally distributed, and the population variances are equal.</p>

<p>\(H_0\): The length of tooth growth by a dose of 0.5 is equivalent to the length of tooth growth by a dose of 1.0 (\(Dose_{0.5} = Dose_{1.0}\)).</p>

<p>\(H_a\): The length of tooth growth by a dose of 0.5 is not equivalent to the length of tooth growth by a dose of 1.0 (\(Dose_{0.5} \neq Dose_{1.0}\)).</p>

<p><strong>Hypothesis testing</strong>:</p>

<pre><code>## 
##  Two Sample t-test
## 
## data:  len by dose
## t = -6.4766, df = 38, p-value = 1.266e-07
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -11.983748  -6.276252
## sample estimates:
## mean in group 0.5   mean in group 1 
##            10.605            19.735
</code></pre>

<p>According to the statistical test, both the lower and upper limit of the confidence interval is smaller than zero, the absolute value of the test statistic is much smaller than <code>qt(.025, 38)</code> = -2.0244, and the p-value is much smaller than the 0.05 threshold.</p>

<p><strong>Conclusion</strong>: The null hypothesis is rejected. The length of tooth growth by a dose of 0.5 is not equivalent to the length of tooth growth by a dose of 1.0 (\(Dose_{0.5} \neq Dose_{1.0}\)).</p>

<h2>5.2 \(Dose_{0.5}\) v.s. \(Dose_{2.0}\)</h2>

<p>Assuming that &quot;len&quot; is an iid variable, the data of tooth growth by dose 0.5 and dose 2.0 are normally distributed, and the population variances are not equal.</p>

<p>\(H_0\): The length of tooth growth by a dose of 0.5 is equivalent to the length of tooth growth by a dose of 2.0 (\(Dose_{0.5} = Dose_{2.0}\)).</p>

<p>\(H_a\): The length of tooth growth by a dose of 0.5 is not equivalent to the length of tooth growth by a dose of 2.0 (\(Dose_{0.5} \neq Dose_{2.0}\)).</p>

<p><strong>Hypothesis testing</strong>:</p>

<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  len by dose
## t = -11.799, df = 36.883, p-value = 4.398e-14
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -18.15617 -12.83383
## sample estimates:
## mean in group 0.5   mean in group 2 
##            10.605            26.100
</code></pre>

<p>According to the statistical test, both the lower and upper limit of the confidence interval is smaller than zero, the absolute value of the test statistic is much smaller than <code>qt(.025, 36.883)</code> = -2.0264, and the p-value is much smaller than the 0.05 threshold.</p>

<p><strong>Conclusion</strong>: The length of tooth growth by a dose of 0.5 is not equivalent to the length of tooth growth by a dose of 2.0 (\(Dose_{0.5} \neq Dose_{2.0}\)).</p>

<h2>5.3 \(Dose_{1.0}\) v.s. \(Dose_{2.0}\)</h2>

<p>Assuming that &quot;len&quot; is an iid variable, the data of tooth growth by dose 1.0 and dose 2.0 are normally distributed, and the population variances are not equal.</p>

<p>\(H_0\): The length of tooth growth by a dose of 1.0 is equivalent to the length of tooth growth by a dose of 2.0 (\(Dose_{1.0} = Dose_{2.0}\)).</p>

<p>\(H_a\): The length of tooth growth by a dose of 1.0 is not equivalent to the length of tooth growth by a dose of 2.0 (\(Dose_{1.0} \neq Dose_{2.0}\)).</p>

<p><strong>Hypothesis testing</strong>:</p>

<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  len by dose
## t = -4.9005, df = 37.101, p-value = 1.906e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -8.996481 -3.733519
## sample estimates:
## mean in group 1 mean in group 2 
##          19.735          26.100
</code></pre>

<p>According to the statistical test, both the lower and upper limit of the confidence interval is smaller than zero, the absolute value of the test statistic is smaller than <code>qt(.025, 37.101)</code> = -2.0260, and the p-value is much smaller than the 0.05 threshold.</p>

<p><strong>Conclusion</strong>: The null hypothesis is rejected. The length of tooth growth by a dose of 1.0 is not equivalent to the length of tooth growth by a dose of 2.0 (\(Dose_{1.0} \neq Dose_{2.0}\)).</p>

<p>\pagebreak</p>

<h1>Appendix</h1>

<h2>Exploratory Plots</h2>

<p><img src="figure/unnamed-chunk-8-1.pdf" alt="Tooth Growth by Different Supp"> </p>

<p><img src="figure/unnamed-chunk-9-1.pdf" alt="Tooth Growth by Different Dose"> </p>

</body>

</html>
